# Generated by Django 5.2.1 on 2025-05-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='books',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.ManyToManyField(to='books.booktype'),
        ),
    ]
