# Generated by Django 4.2.21 on 2025-05-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_author_books_remove_book_book_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(blank=True, to='books.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.ManyToManyField(blank=True, to='books.booktype'),
        ),
    ]
